- docs/.vitepress/config.mts
This PR enables VitePress option to [generate clean](https://vitepress.dev/guide/routing#generating-clean-url), beautiful links without the `.html` postfix.
❌ Before:
https://herb-tools.dev/bindings/javascript/reference.html
✅ After:
https://herb-tools.dev/bindings/javascript/reference
> Clean URLs: (remove .html postfix from the links)

- src/extract.c
- test/extractor/extract_ruby_test.rb
- test/parser/erb_test.rb
- test/snapshots/parser/erb_test/test_0015_comment_e95f45b0f3e230c24e11f4b083de23f5.txt
- test/snapshots/parser/erb_test/test_0016_multi-line_comment_14c1f84ba7b4627b3e0dc3ba74179bb8.txt
- test/snapshots/parser/erb_test/test_0017_multi-line_comment_with_Ruby_keyword_dd7885019a51280cc6cfef734bf1161a.txt
This pull request updates the `herb_extract_ruby` and `herb_extract_ruby_to_buffer_with_semicolons` methods in `extract.c` to not extract the content of ERB Comment Nodes (`<%#`) as Ruby code.
So a source file like this:
```html+erb
<%# This is a comment %>
<h1><%= title %></h1>
```
Was extracted to Ruby code as:
```ruby
title        
```
With the changes included in this pull request it's going to be:
```ruby
title  
```        
This is in order to resolve #91. It's valid to have multi-line ERB Comments like:
```html+erb
<%#
This is 
a comment
over multiple
lines
%>
```
Which before this pull request was extracted to Ruby as:
```ruby
#
This is 
a comment
over multiple
lines
```
Which is not a valid Ruby comment anymore, but treated as actual Ruby code from the second line on. If the …
> Don't extract ERB comments as Ruby comments in `herb_extract_ruby`

- src/analyzed_ruby.c
- templates/src/ast_nodes.c.erb
This pull request implements a proper cleanup procedure for `analyzed_ruby_T` structs by implementing the `free_analyzed_ruby` function in `src/analyzed_ruby.c` and calling it in the AST Node `free` function for Nodes with `Herb::Template::AnalyzedRubyField` fields (namely `ERBContentNode`).
> Implement `free_analyzed_ruby` function

- ext/herb/extension.c
- ext/herb/extension_helpers.c
- javascript/packages/node/extension/extension_helpers.cpp
- javascript/packages/node/extension/herb.cpp
- wasm/extension_helpers.cpp
- wasm/herb-wasm.cpp
This pull request improves the memory management in all language-bindings by adding explicit calls to free allocated resources after creating the `LexResult` and `ParseResult` objects. 
There's a good chance that this is part of the reason why we are seeing the issues in #103.
> Free C Structs after creating Lex and Parse Results

- lib/herb/project.rb
This pull request improves the output of the `herb analyze` CLI command by adding a percentage for each status.
/cc @dennispaagman
> Add percentage to `herb analyze` CLI output

- src/analyze.c
- src/extract.c
This pull request focuses on improving memory management and ensuring proper cleanup of dynamically allocated resources in `src/analyze.c` and `src/extract.c`. The changes add missing cleanup calls to prevent memory leaks.
> Memory management improvements in `analyze.c` and `extract.c`

- .gitignore
- .rubocop.yml
- lib/herb.rb
- lib/herb/ast/node.rb
- lib/herb/parse_result.rb
- sig/herb/ast/node.rbs
- sig/herb/ast/nodes.rbs
- sig/herb/parse_result.rbs
- sig/herb/visitor.rbs
- templates/lib/herb/ast/nodes.rb.erb
- templates/lib/herb/visitor.rb.erb
- test/visitor_test.rb
This pull request introduces a `Herb::Visitor` class to the ruby gem, enabling traversal of the AST by writing a visitor class that inherits from `Herb::Visitor`.
```ruby
class TextNodeVisitor < Herb::Visitor
def visit_html_text_node(node)
puts "HTML TextNode #{node.content}"
end
end
visitor = TextNodeVisitor.new
result = Herb.parse("<p>Hello <%= user.name %></p>")
result.visit(visitor)
```
> Implement `Herb::Visitor` in Ruby gem

- ext/herb/extension.c
- ext/herb/extension.h
- ext/herb/extension_helpers.c
This pull request refactors the `Herb` Ruby C extension to centralize the definitions of module and class constants. This reduces redundancy and any issues that might arise from redefining the constants on every call.
> Refactor Ruby extension to reuse constants

- lib/herb/ast/node.rb
- sig/herb/ast/node.rbs
- sig/herb/ast/nodes.rbs
- templates/lib/herb/ast/nodes.rb.erb
- templates/lib/herb/visitor.rb.erb
- test/visitor_test.rb
This pull request introduces changes to improve the handling of `nil` values in `child_nodes` when traversing a tree using a Visitor. The `compact_child_nodes` method filters out `nil` values so that the visitor can call that method without having to handle nil values there.
Previously this would fail with something like:
```
NoMethodError: undefined method 'accept' for nil
lib/herb/visitor.rb:21:in 'block in Herb::Visitor#visit_child_nodes'
lib/herb/visitor.rb:21:in 'Array#each'
lib/herb/visitor.rb:21:in 'Herb::Visitor#visit_child_nodes'
test/visitor_test.rb:16:in 'VisitorTest::VisitedNodesVisitor#visit_child_nodes'
lib/herb/visitor.rb:51:in 'Herb::Visitor#visit_html_element_node'
lib/herb/ast/nodes.rb:344:in 'Herb::AST::HTMLElementNode#accept'
lib/herb/visitor.rb:21:in 'block in …
```
> Implement `Herb::Node#compact_child_nodes`

- src/buffer.c
- src/include/buffer.h
- test/c/test_buffer.c
This pull request refactors the buffer management system in `src/buffer.c` and updates its corresponding tests. The changes improve the clarity of function names, introduce new helper functions for managing buffer capacity, and enhance error handling.
Replaced `buffer_increase_capacity` with `buffer_expand_if_needed`, which dynamically adjusts buffer capacity based on required length. Introduced new helper functions `buffer_resize`, `buffer_expand_capacity`, and `buffer_has_capacity` for more modular buffer operations. Improved error handling by using `exit(1)` for critical failures.
Alternative to #118
Might close #103 
Might close #121
> Increase buffer capacity safely and handle overflow errors

- src/parser.c
- test/parser/erb_test.rb
- test/snapshots/parser/erb_test/test_0018_erb_output_wrapped_in_double_quotes_81968725d5b5d72882f6ae09a80071b7.txt
- test/snapshots/parser/erb_test/test_0019_erb_output_wrapped_in_single_quotes_aa9928aed6dc45d5fd983a3030e6c4ad.txt
- test/snapshots/parser/erb_test/test_0020_erb_output_wrapped_in_double_quotes_inside_if_8194229e22f698062f184c58c874d6d1.txt
- test/snapshots/parser/erb_test/test_0021_erb_output_wrapped_in_single_quotes_inside_if_5332acffecc53cb1b561a5e02e44e8fa.txt
This pull request introduces support for parsing ERB tags wrapped in quotes (both single and double) by adding `TOKEN_QUOTE` to the list of token types in the `parser_parse_in_data_state` function.
So that we now can successfully parse documents like:
```html+erb
"<%= value %>"
```
Fixes #141
> Fix parser to handle quotes around ERB output as text content

- src/parser.c
- test/parser/attributes_test.rb
- test/snapshots/parser/attributes_test/test_0008_style_attribute_with_url_02762c59a138badb5bfea6b275ae6251.txt
- test/snapshots/parser/attributes_test/test_0009_double_quotes_inside_single_quotes_cbaae19549457c1f74162c0f28dbb022.txt
- test/snapshots/parser/attributes_test/test_0010_multiple_nested_quotes_fbfe8fcce107a09add4af69465c4037d.txt
- test/snapshots/parser/attributes_test/test_0011_empty_quoted_attribute_values_8cbc6c3a58ce6e2fd57c03326bec1b73.txt
- test/snapshots/parser/attributes_test/test_0012_mixed_quote_types_in_multiple_attributes_c8a24bb6a12da051002e130b8c94b4b4.txt
- test/snapshots/parser/attributes_test/test_0013_erb_output_with_quotes_fb1d0c6f864f1f46ac83f42d1250c9ad.txt
This pull request improves the parsing of quoted HTML attribute values and adds tests for various cases involving quotes in attribute values. 
Resolves #146
> Improve parsing of attribute values with quotes

- javascript/packages/linter/src/rules/html-attribute-double-quotes.ts
- javascript/packages/linter/src/rules/html-attribute-values-require-quotes.ts
- javascript/packages/linter/src/rules/html-boolean-attributes-no-value.ts
- javascript/packages/linter/src/rules/html-img-require-alt.ts
- javascript/packages/linter/src/rules/html-no-duplicate-attributes.ts
- javascript/packages/linter/src/rules/html-tag-name-lowercase.ts
- javascript/packages/linter/test/rules/html-attribute-double-quotes.test.ts
- javascript/packages/linter/test/rules/html-attribute-values-require-quotes.test.ts
- javascript/packages/linter/test/rules/html-boolean-attributes-no-value.test.ts
- javascript/packages/linter/test/rules/html-img-require-alt.test.ts
- javascript/packages/linter/test/rules/html-no-block-inside-inline.test.ts
- javascript/packages/linter/test/rules/html-no-duplicate-attributes.test.ts
- javascript/packages/linter/test/rules/html-no-nested-links.test.ts
- javascript/packages/linter/test/rules/html-tag-name-lowercase.test.ts
This pull request updates error messages across several HTML linting rules to use backticks for improved readability and consistency. It also updates corresponding test cases to verify the modified error messages.
> Improve formatting of Linter messages

- wasm/Makefile
This pull request removes the `src/main.c` file from the WebAssembly builds, since everytime you imported the library it would `console.log` the arguments/output from the C-CLI which is in `main.c`:
```
❯ yarn test
yarn run v1.22.22
$ vitest run
RUN  v3.1.4 /Users/marcoroth/Development/herb-linter/javascript/packages/browser
stdout | test/browser.test.ts > @herb-tools/browser
./herb [command] [options]
stdout | test/browser.test.ts > @herb-tools/browser
stdout | test/browser.test.ts > @herb-tools/browser
Herb 🌿 Powerful and seamless HTML-aware ERB parsing and tooling.
stdout | test/browser.test.ts > @herb-tools/browser
stdout | test/browser.test.ts > @herb-tools/browser
./herb lex [file]      -  Lex a file
stdout | test/browser.test.ts > @herb-tools/browser
./herb lex_json [file] -  Lex a …
```
> Exclude `main.c` from WebAssembly builds

- javascript/packages/linter/src/linter.ts
- javascript/packages/linter/src/rules/html-attribute-double-quotes.ts
- javascript/packages/linter/src/rules/html-attribute-values-require-quotes.ts
- javascript/packages/linter/src/rules/html-boolean-attributes-no-value.ts
- javascript/packages/linter/src/rules/html-img-require-alt.ts
- javascript/packages/linter/src/rules/html-no-block-inside-inline.ts
- javascript/packages/linter/src/rules/html-no-duplicate-attributes.ts
- javascript/packages/linter/src/rules/html-no-nested-links.ts
- javascript/packages/linter/src/rules/html-tag-name-lowercase.ts
- javascript/packages/linter/src/rules/rule-utils.ts
- javascript/packages/linter/src/types.ts
- javascript/packages/linter/test/linter.test.ts
- javascript/packages/linter/test/rules/html-attribute-double-quotes.test.ts
- javascript/packages/linter/test/rules/html-attribute-values-require-quotes.test.ts
- javascript/packages/linter/test/rules/html-boolean-attributes-no-value.test.ts
- javascript/packages/linter/test/rules/html-img-require-alt.test.ts
- javascript/packages/linter/test/rules/html-no-block-inside-inline.test.ts
- javascript/packages/linter/test/rules/html-no-duplicate-attributes.test.ts
- javascript/packages/linter/test/rules/html-no-nested-links.test.ts
- javascript/packages/linter/test/rules/html-tag-name-lowercase.test.ts
This pull request refactors the `Linter` class and all linting rules in the `@herb-tools/linter` package to simplify and improve their design. The changes focus on removing unnecessary code, introducing reusable utilities, and enhancing maintainability by adopting visitor-based patterns and removing direct dependencies on specific node types.
> Refactor Linter and Linter Rules

- javascript/packages/linter/src/cli.ts
- javascript/packages/linter/test/__snapshots__/cli.test.ts.snap
This pull request shows the total number of issues (error count + warnings count) in the summary of the lint run.
```diff
❯ bin/herb-lint test/fixtures/
[...]
Checked     4 files
Files       3 with issues | 1 clean (4 total)
- Issues      7 errors | 0 warnings (across 3 files)
+ Issues      7 errors | 0 warnings (7 issues across 3 files)
Start at    03:45:41
Duration    33ms (8 rules)
```
> Show total number of issues in Herb Lint CLI

- javascript/packages/linter/src/cli.ts
- javascript/packages/linter/test/__snapshots__/cli.test.ts.snap
- javascript/packages/linter/test/cli.test.ts
- javascript/packages/linter/test/fixtures/few-rule-violations.html.erb
- javascript/packages/linter/test/fixtures/multiple-rule-violations.html.erb
This pull request renames "Issues" to "Violations" in the Herb Lint CLI. It now also lists the rule names of the violated rules. If there are more than 5 violated rules it will show the "Most violated rules" including a summary of how many more there were:
Rule violations:
Most violated rules:
> Rename to violations in Herb Lint CLI and show violated rule names

- javascript/packages/linter/src/cli.ts
- javascript/packages/linter/src/linter.ts
- javascript/packages/linter/src/rules/erb-no-empty-tags.ts
- javascript/packages/linter/src/rules/erb-no-output-control-flow.ts
- javascript/packages/linter/src/rules/html-anchor-require-href.ts
- javascript/packages/linter/src/rules/html-attribute-double-quotes.ts
- javascript/packages/linter/src/rules/html-attribute-values-require-quotes.ts
- javascript/packages/linter/src/rules/html-boolean-attributes-no-value.ts
- javascript/packages/linter/src/rules/html-img-require-alt.ts
- javascript/packages/linter/src/rules/html-no-block-inside-inline.ts
- javascript/packages/linter/src/rules/html-no-duplicate-attributes.ts
- javascript/packages/linter/src/rules/html-no-empty-headings.ts
- javascript/packages/linter/src/rules/html-no-nested-links.ts
- javascript/packages/linter/src/rules/html-tag-name-lowercase.ts
- javascript/packages/linter/src/rules/rule-utils.ts
- javascript/packages/linter/src/types.ts
- javascript/packages/linter/test/linter.test.ts
- javascript/packages/linter/test/rules/erb-no-empty-tags.test.ts
- javascript/packages/linter/test/rules/erb-no-output-control-flow.test.ts
- javascript/packages/linter/test/rules/html-anchor-require-href-rule.test.ts
- javascript/packages/linter/test/rules/html-attribute-double-quotes.test.ts
- javascript/packages/linter/test/rules/html-attribute-values-require-quotes.test.ts
- javascript/packages/linter/test/rules/html-boolean-attributes-no-value.test.ts
- javascript/packages/linter/test/rules/html-img-require-alt.test.ts
- javascript/packages/linter/test/rules/html-no-block-inside-inline.test.ts
- javascript/packages/linter/test/rules/html-no-duplicate-attributes.test.ts
- javascript/packages/linter/test/rules/html-no-empty-headings.test.ts
- javascript/packages/linter/test/rules/html-no-nested-links.test.ts
- javascript/packages/linter/test/rules/html-tag-name-lowercase.test.ts
Following up on #227, this pull request renames all properties and functions in the Linter from `message` to `offense`.
> Rename `message` to `offense` in Linter

- javascript/packages/core/src/diagnostic.ts
- javascript/packages/core/src/index.ts
- javascript/packages/linter/src/rules/rule-utils.ts
- javascript/packages/linter/src/types.ts
- playground/src/controllers/playground_controller.js
- templates/javascript/packages/core/src/errors.ts.erb
This pull request introduces a new `Diagnostics` interface which will be used to represent errors, warnings, info messages, lint offenses, and anything else that could be shown in the editor as a "Diagnostic".
Previously we had a `HerbDiagnostic` type, which we used to convert "errors" to "diagnostics" so they would be compatible with the Monaco editor in the playground.
Now we renamed that `HerbDiagnostic` type to `MonacoDiagnostic` so it's clear what this one is used for. With that, we also introduced a new `toMonacoDiagnostic(diagnostic: Diagnostic): MonacoDiagnostic` utility function to convert any `Diagnostic` to a `MonacoDiagnostic`.
There are probably also some refactoring opportunities to make use of these new types in the Language Server.
> Add `Diagnostics` interface and rename other to `MonacoDiagnostic`

- lib/herb/cli.rb
- lib/herb/project.rb
This pull request adds timing to the `herb analyze` command to track total execution time. Additionally it also add a `--no-timing` option to disable timing output
```diff
Completed processing all files.
\--- SUMMARY --------------------------------------------------------------------
Total files: 145
✅ Successful: 144 (99.3%)
❌ Failed: 0 (0.0%)
⚠️  Parse errors: 1 (0.7%)
⏱️  Timed out: 0 (0.0%)
Files with parse errors:
- app/views/contributions/index.html.erb
+
+⏱️  Total time: 535.81ms
```
> Add timing functionality to `herb analyze` command

- src/analyze_helpers.c
- test/analyze/ternary_test.rb
- test/snapshots/analyze/ternary_test/test_0001_ternary_operator_in_ERB_output_tag_487f1093637a362df78bafb89af97d09.txt
- test/snapshots/analyze/ternary_test/test_0002_complex_ternary_operator_with_method_calls_c9fd4eebccb37e967b174ccf1bde7bf2.txt
- test/snapshots/analyze/ternary_test/test_0003_ternary_operator_in_form_with_3e5154d12d6259cc2ac2da74fc48e803.txt
- test/snapshots/analyze/ternary_test/test_0004_nested_ternary_operators_b02fe2f695043e3ef415f674581f8187.txt
- test/snapshots/analyze/ternary_test/test_0005_ternary_operator_in_attribute_value_d0b1eb0c3aae3bb30cf7891afdac44b8.txt
- test/snapshots/analyze/ternary_test/test_0006_multiple_ternary_operators_in_same_ERB_tag_7dd1d18fe401ed6c61c478be9ee5140f.txt
- test/snapshots/analyze/ternary_test/test_0007_ternary_operator_with_blocks_a8c8a50604f8821739b2814b58b652f2.txt
- test/snapshots/analyze/ternary_test/test_0008_form_with_helper_with_ternary_in_url_parameter_e554d08ac7e5da90cd046d79030c2a44.txt
- test/snapshots/analyze/ternary_test/test_0009_content_tag_with_ternary_for_class_attribute_910f82cb9ee5855d1c51c08667ac90d5.txt
- test/snapshots/analyze/ternary_test/test_0010_content_tag_with_ternary_for_data_attribute_6f00128b70c7d3176646995151ecfcaa.txt
- test/snapshots/analyze/ternary_test/test_0011_form_with_with_complex_ternary_in_multiple_attributes_0db72f423bc1543d78016121e43409d3.txt
- test/snapshots/analyze/ternary_test/test_0012_inline_if_modifier_in_ERB_output_tag_b4d740369619f1d7bde41172ac6933e6.txt
- test/snapshots/analyze/ternary_test/test_0013_inline_unless_modifier_in_ERB_output_tag_982863841843053cc3728f62e00fa523.txt
This pull request fixes an issue where ternary operators in `ERBContentNode` were incorrectly transformed into `ERBIfNode` structures. The parser now properly distinguishes between ternary operators and regular if statements by checking if the `if_keyword_loc` is present in the Prism AST node.
```erb
<%= form_with model: @post, url: @post.new_record? ? posts_path : post_path(@post) do |f| %>
Content
<% end %>
```
Now:
```js
@ DocumentNode (location: (1:0)-(4:0))
└── children: (2 items)
├── @ ERBBlockNode (location: (1:0)-(3:9))
│   ├── tag_opening: "<%=" (location: (1:0)-(1:3))
│   ├── content: " form_with model: @post, url: @post.new_record? ? posts_path : post_path(@post) do |f| " (location: (1:3)-(1:90))
│   ├── tag_closing: "%>" (location: (1:90)-(1:92))
│   ├── body: (1 item)
│   │ …
```
> Fix ternary operators being transformed into `ERBIfNode`

- javascript/packages/language-server/package.json
- javascript/packages/language-server/src/linter_service.ts
- javascript/packages/language-server/src/settings.ts
- javascript/packages/language-server/test/linter_service.test.ts
- javascript/packages/language-server/test/settings.test.ts
Add default linter configuration to prevent TypeError when clients like Helix don't provide settings configuration. This ensures the language server works out of the box without requiring a `.herb-lsp/config.json` file.
Fixes #244
> Fix error in language server when linter settings are not provided

- docs/.vitepress/config/theme.mts
- docs/docs/integrations/editors.md
- docs/docs/integrations/editors/sublime.md
- javascript/packages/language-server/README.md
Just what the title says! Uses the logo from https://github.com/marcoroth/herb/commit/be53b87d2ab98b604704a7ec35862d260a07a548
> docs: add documentation for using Herb in Sublime Text via Sublime LSP

- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/html/attributes.test.ts
- yarn.lock
Formatter was stripping inline ERB conditionals like 
```erb
<span<% if condition %>class='x'<% end %>>
```
Now correctly preserves and formats them with proper spacing.
Fixes #249
> fix: preserve inline ERB conditionals in HTML tags

- javascript/packages/linter/src/default-rules.ts
This pull request disables the `html-no-block-inside-inline` rule, introduced in #164, for now.
See https://github.com/marcoroth/herb/issues/260
See https://github.com/marcoroth/herb/issues/255
See https://github.com/marcoroth/herb/issues/248
> Disable `html-no-block-inside-inline` rule for now

- javascript/packages/vscode/esbuild.js
- javascript/packages/vscode/src/parse-worker.js
The Herb version installed from the visual studio extension store would show all files as "parse errors". This pull request:
- replaces dynamic imports with static requires in parse-worker.js
- bundles worker separately with all dependencies using esbuild
- removes simple file copy in favor of proper bundling
This ensures the worker functions correctly when the extension is installed from a VSIX file.
> VS Code Extension: Fix worker bundling for VSIX distribution

- javascript/packages/formatter/src/cli.ts
- javascript/packages/formatter/test/cli.test.ts
- javascript/packages/language-server/src/formatting_service.ts
Files formatted by the CLI now properly end with a newline for better file formatting standards while keeping the formatter API unchanged.
> Formatter: Ensure CLI output ends with trailing newline

- javascript/packages/linter/README.md
This PR corrects how rules are passed to the Linter in the JavaScript customization example.
> Fix how to instantiate specific rules in the Javascript customization example

- javascript/packages/formatter/src/cli.ts
- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/cli.test.ts
- javascript/packages/formatter/test/erb/erb.test.ts
- javascript/packages/formatter/test/erb/for.test.ts
- javascript/packages/formatter/test/erb/until.test.ts
- javascript/packages/formatter/test/erb/while.test.ts
- javascript/packages/formatter/test/html/attributes.test.ts
- javascript/packages/formatter/test/html/text-content.test.ts
- javascript/packages/formatter/test/options.test.ts
This pull request improves the formatter to make smarter decisions when inlining/splitting the line based on content complexity and nesting depth.
**Simple elements now stay inline**
Before:
```html
<h1>
hello
</h1>
<div>
Hello World
</div>
<p>
Simple text
</p>
```
After:
```html
<h1>hello</h1>
<div>Hello World</div>
<p>Simple text</p>
```
**Mixed content with inline elements stays inline**
Before:
```html
<p>
hello
<b>
bold
</b>
world
</p>
<div>
Text with
<strong>
strong
</strong>
and
<em>
emphasis
</em>
</div>
```
After:
```html
<p>hello <b>bold</b> world</p>
<div>Text with <strong>strong</strong> and <em>emphasis</em></div>
```
**Deep nesting (2+ levels) splits appropriately**
Before:
```html
<h1>
<b>
<i>
hello
</i>
</b>
</h1>
```
After:
```html
<h1>
<b>
<i>hello</i>
</b>
</h1>
``` …
> Formatter: Keep simple element children inline instead of splitting them up

- javascript/packages/linter/src/rules/erb-require-whitespace-inside-tags.ts
- javascript/packages/linter/test/rules/erb-require-whitespace-inside-tags.test.ts
- test/parser/erb_test.rb
- test/snapshots/parser/erb_test/test_0026_erb_comment_with_equals_sign_312beb21c876bb87e5bbb8c9288a5bd1.txt
- test/snapshots/parser/erb_test/test_0027_erb_comment_with_equals_sign_without_spaces_be2c65ad965090f17c18896f988e85a9.txt
- test/snapshots/parser/erb_test/test_0028_multi-line_erb_comment_with_equals_sign_bb3c3c1637a687e1d87a90a893fa09fd.txt
This pull request updates the `erb-require-whitespace-inside-tags` rule to properly check whitespace after the `#` in ERB comment tags.
- `<%# comment %>` requires space after `#`
- `<%#= comment %>` requires space after `=`
- `<%#comment %>` and `<%#=comment %>` are flagged as offenses
Fixes #297
> Fix `erb-require-whitespace-inside-tags` rule for comment tags

- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/erb/erb.test.ts
> Formatter: Fix case where formatter would output `% %>`

- javascript/packages/language-server/src/formatting_service.test.ts
- javascript/packages/language-server/src/formatting_service.ts
This pull requst adds safe navigation to prevent null reference errors when settings object is null. This pull request also adds comprehensive tests to ensure the service works properly.
Resolves https://github.com/marcoroth/herb/issues/290
> Language Server: Fix `FormattingService` when settings are not available

- javascript/packages/language-server/src/formatting_service.test.ts
- javascript/packages/language-server/src/formatting_service.ts
- javascript/packages/language-server/src/server.ts
This pull request implements the `textDocument/rangeFormatting` request in the language server, which allows to only format selected lines.
This also works when you have the formatter disabled globally but want to just format a selection by running the `Format Selection` command manually:
https://github.com/user-attachments/assets/2502ccb5-9986-4f7b-860d-1948bb90bcda
Resolves #317
> Add `textDocument/rangeFormatting` support to language server

- javascript/packages/language-server/src/formatting_service.ts
- javascript/packages/language-server/test/formatting_service.test.ts
This pull request improves the range formatting functionality introduced in #319 by calculating the minimum indentation across all selected lines, then stripping the minimum indentation before formatting (to prevent over-indenting) and then re-applying the minimum indentation to all formatted lines so it stays in-place and doesn't get dedented all the way to the beginning of the line.
**Before:**
https://github.com/user-attachments/assets/d5aea24d-9090-447c-aff8-a3ae17f767b6
**After:**
https://github.com/user-attachments/assets/21001f36-f337-49fa-847e-2f59cbd1bfc1
/cc @excid3
> Improve range formatting to preserve minimum indentation

- src/parser.c
- test/parser/text_content_test.rb
- test/snapshots/parser/tags_test/test_0027_stray_closing_tag_with_whitespace_0ee4b96cac701f87a8b6cb0cf5ad48bc.txt
- test/snapshots/parser/text_content_test/test_0024_non-breaking_space_(U+00A0)_as_only_content_171ed99b0854aa35f50c3371b07fffcc.txt
- test/snapshots/parser/text_content_test/test_0025_non-breaking_space_mixed_with_ERB_-_issue_310_1f905e5ab087b22e76444d7e98132e6d.txt
- test/snapshots/parser/text_content_test/test_0026_multiple_non-breaking_spaces_in_text_7a2675aa6ba4cdbc5080233628d5e45e.txt
- test/snapshots/parser/text_content_test/test_0027_non-breaking_space_in_attribute_value_4ef6c07c78dcc312066ef682f96c0253.txt
This pull requst adds support for non-breaking space (U+00A0) characters in HTML content. Previously they were not recognized as valid text content, causing unexpected token errors.
Fixes #310
> Parser: Add support for `TOKEN_NBSP` in HTML content

- src/parser.c
- test/parser/text_content_test.rb
- test/snapshots/parser/tags_test/test_0027_stray_closing_tag_with_whitespace_0ee4b96cac701f87a8b6cb0cf5ad48bc.txt
- test/snapshots/parser/text_content_test/test_0028_at_symbol_(@)_in_text_content_-_issue_285_b4af64f3ea734ed4c7510e7e5738841a.txt
- test/snapshots/parser/text_content_test/test_0029_at_symbol_at_beginning_of_text_b0241d43408d1826ae74f1bbec2e6413.txt
- test/snapshots/parser/text_content_test/test_0030_multiple_at_symbols_in_text_33e06a6d495e2d066b5a1a7be86f91c1.txt
- test/snapshots/parser/text_content_test/test_0031_at_symbol_mixed_with_ERB_a4b70c6afcd72595d84b1468a8b61d3a.txt
- test/snapshots/parser/text_content_test/test_0032_at_symbol_in_attribute_value_e5290cd6e77d3872131d3aa211bea034.txt
This pull requst adds support for the `@` character in HTML content. Previously it wasn't recognized as valid text content, causing unexpected token errors.
**Example**
```html
<span>@username</span>
```
**Before**
```js
@ DocumentNode (location: (1:0)-(1:22))
├── errors: []
└── children: (1 item)
└── @ HTMLElementNode (location: (1:0)-(1:22))
├── errors: (1 item)
│   └── @ UnexpectedError (location: (1:6)-(1:7))
│       ├── message: "Unexpected token. Expected: `TOKEN_ERB_START, TOKEN_HTML_DOCTYPE, TOKEN_HTML_COMMENT_START, TOKEN_IDENTIFIER, TOKEN_WHITESPACE, TOKEN_NBSP, or TOKEN_NEWLINE`, found: `TOKEN_AT`."
│       ├── description: "Unexpected token"
│       ├── expected: "TOKEN_ERB_START, TOKEN_HTML_DOCTYPE, TOKEN_HTML_COMMENT_START, TOKEN_IDENTIFIER, TOKEN_WHITESPACE, TOKEN_NBSP, or …
```
> Parser: Add support for `TOKEN_AT` in HTML content

- src/parser.c
- test/parser/attributes_test.rb
- test/snapshots/parser/attributes_test/test_0014_attributes_with_dots_in_name_89984a18a28d8c5c73db29753dc762c2.txt
- test/snapshots/parser/attributes_test/test_0015_complex_attribute_with_dots_and_values_d5cd679cddf6b4eae3a0c22c008acaae.txt
This pull request adds support for parsing a period in HTML attribute names. So we can now properly parse snippets like this: 
```erb
<div x-transition.duration.500ms></div>
```
Technically this is not fully compliant HTML5, but popular frameworks like Alpine.js leverage this syntax and it mostly seem to work in browsers.
But even if we wouldn't want to allow this kind of syntax, we'd still need to parse it this way so we could write linter rules to help people avoid this kind of syntax if strict HTML5-compliance is required.
Resolves https://github.com/marcoroth/herb/issues/287
> Allow HTML Attribute Names to have a period in the attribute name

- src/parser.c
- test/parser/attributes_test.rb
- test/snapshots/parser/attributes_test/test_0006_attribute_value_with_space_after_equal_sign_60301c34c290d45874e5f104c39feb48.txt
- test/snapshots/parser/attributes_test/test_0016_attributes_starting_with_@_symbol_90ae5bd03544cde697c6898cc52d03a7.txt
- test/snapshots/parser/attributes_test/test_0017_@_attributes_with_various_patterns_1c9d04c71dfedc10b544c42b3452367c.txt
- test/snapshots/parser/attributes_test/test_0018_standalone_@_symbol_in_div_tag_0fac4a8abe9de4433967e825056a4635.txt
- test/snapshots/parser/attributes_test/test_0019_standalone_@_symbol_followed_by_whitesapce_in_div_tag_651fc560524277c36845d3e3e3cb01ae.txt
- test/snapshots/parser/attributes_test/test_0020_standalone_@_symbol_followed_by_whitesapce_and_identifier_in_div_tag_1f97e198235e78d1a25174baf6e1973d.txt
- test/snapshots/parser/attributes_test/test_0021_standalone_@_symbol_in_div_tag_followed_by_attribute_b71e23ffa38851540e408d9383abd12c.txt
- test/snapshots/parser/attributes_test/test_0022_atttribute_with_@_prefix_and_now_value_6583f84753df8346dcd916f07301fc6b.txt
- test/snapshots/parser/tags_test/test_0016_colon_inside_html_tag_b7b46dcd10fad620a00a95b27daab204.txt
This pull request improves the way parser handles Alpine.js-like attributes where the attribute name starts with a `@` sign. 
Previously, the parser would fail to parse HTML templates containing attributes such as `@click`, `@keyup.enter`, or `@change.debounce.100ms`, which are commonly used in Alpine.js and Vue.js applications.
The pull request extends the existing attribute name parsing logic to recognize `@` tokens as valid starting characters for attribute names.
> Parser: Add support for `@` token in HTML attribute names

- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/erb/whitespace-formatting.test.ts
This pull request fixes an issue where ERB tags like `<% if disabled%>` and `<%end%>` would be formatted without proper spacing when being used/rendered inside HTML tags/inline contexts.
Now it correctly formats them as `<% if disabled %>` and `<% end %>`.
**Example**
```erb
<a href=""<%if disabled%>class="disabled"<%end%>>Text</a>
```
**Before**
```erb
<a href="" <%if disabled%> class="disabled" <%end%>>
Text
</a>
```
**After**
```erb
<a href="" <% if disabled %> class="disabled" <% end %>>
Text
</a>
```
> Formatter: Fix ERB whitespace formatting in inline contexts

- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/html/attributes.test.ts
This pull request fixes the formatter to correctly handle ERB expressions within HTML attribute values. Previously, the formatter would incorrectly move closing tags inside quoted attribute values.
**Input:**
```erb
<data value="<%= @post.external %>"></data>
```
**Before:**
```erb
<data value="<%= @post.external %></data>">
```
**After:**
```erb
<data value="<%= @post.external %>"></data>
```
The fix uses AST-based tag construction instead of string manipulation to ensure proper quote boundaries.
Resolves https://github.com/marcoroth/herb/issues/250
> Formatter: Fix ERB quote misplacement in HTML attributes

- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/cli.test.ts
- javascript/packages/formatter/test/document-formatting.test.ts
- javascript/packages/formatter/test/erb/whitespace-formatting.test.ts
- javascript/packages/formatter/test/html/inline-elements.test.ts
- javascript/packages/formatter/test/html/text-content.test.ts
This pull request improves the formatter by addressing two critical formatting issues. First, it resolves the problem described in issue #251 where inline elements within text flow were being unnecessarily broken across multiple lines, disrupting the visual presentation of content like `Em<em>pha</em>sis`. 
The formatter now correctly identifies text flow contexts and preserves inline elements on the same line as their surrounding text.
Second, it fixes spacing issues with ERB conditional attributes in HTML tags. Previously, ERB conditionals like `<span<% if condition %>class="active"<% end %>></span>` were being formatted with double spaces between ERB tag closings and attributes. 
The root cause was that ERB control flow nodes in HTML tag contexts were not being processed in inline …
> Formatter: Fix inline element and ERB conditional attributes formatting

- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/html/quote-normalization.test.ts
This pull request changes the formatter to normalize single quotes to double quotes in HTML attributes when safe.
It also adds quotes to unquoted attribute values for consistency and preserves single quotes when attribute values contain double quotes.
**Example**
```html
<input value=test type='text' data-value='Value with double (") quote' disabled />
```
**Output**
```html
<input value="test" type="text" data-value='Value with double (") quote' disabled />
```
> Formatter: Add HTML attribute quote normalization

- javascript/packages/language-server/src/diagnostics.ts
- javascript/packages/language-server/src/linter_service.ts
- javascript/packages/language-server/test/linter_service.test.ts
This pull request refactors the `LinterService.lintDocument()` function and removes the now unused `DocumentNode` argument.
> Remove unused argument in `LinterService.lintDocument`

- javascript/packages/linter/src/rules/html-aria-level-must-be-valid.ts
- javascript/packages/linter/test/rules/html-aria-level-must-be-valid.test.ts
This pull request improves the `html-aria-level-must-be-valid` linter rule introduced in #338 to also flag empty `aria-level` attributes.
After this change, it will now also flag this snippet:
```html
<div role="heading" aria-level="">Empty value</div>
```
> Handle empty attribute case for `html-aria-level-must-be-valid` rule

- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/erb/case.test.ts
This pull request adds support for formatting `case/in` statements.
Previously it would only format the `case` line and omit all `in` nodes. Now an input like:
```erb
<% case { hash: { nested: '4' } } %>
<% in { hash: { nested: } } %>
<span>there</span>
<% in { another: } %>
<span>there</span>
<% in { yet_another: { nested: } } %>
<span>hi</span>
<% else %>
<span>there</span>
<% end %>
```
Will now format as:
```erb
<% case { hash: { nested: '4' } } %>
<% in { hash: { nested: } } %>
<span>there</span>
<% in { another: } %>
<span>there</span>
<% in { yet_another: { nested: } } %>
<span>hi</span>
<% else %>
<span>there</span>
<% end %>
```
> Formatter: Support formatting `case`/`in` statements

- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/html/attribute-formatting.test.ts
- javascript/packages/formatter/test/html/quote-normalization.test.ts
This pull request improves the formatter by improving the way we format attribute values based on their semantic meaning and the HTML tag they belong to.
Previously, all attributes were either left as-is or formatted the same way. Now we have intelligent formatting that:
- Formats `class` attributes with multiline breaking for readability
- Normalizes `srcset` and `sizes` attributes on `img` tags by collapsing whitespace
- Preserves all other attributes exactly as-is to maintain their intended formatting (maybe we can expand the list of supported attributes in the future)
For example, an input like:
```html
srcset="image-480w.jpg 480w,
image-800w.jpg 800w,
image-1200w.jpg 1200w"
style="background: linear-gradient(45deg,
red 0%,
blue 100%);">
```
Before:
```html
image-800w.jpg 800w, …
```
> Formatter: Implement tag-specific attribute formatting

- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/html/unicode-characters.test.ts
This pull request improves the way the formatter handles multi-byte UTF-8 characters when formatting a document.
When multi-byte UTF-8 characters appear before a HTML or ERB comment in a document it would corrupt printing the comments since they used string slicing instead of actually using the content from the AST node.
The fix replaces the source string slicing with direct AST node content reconstruction.
This also gave me the opportunity to finally remove these `// TODO: use .value` which in the end was why this bug existed in the first place:
https://github.com/marcoroth/herb/blob/02a1389b22c9ed2013085fc9fc49c9e0e253b346/javascript/packages/formatter/src/printer.ts#L954
Resolves #360
> Formatter: Fix multi-byte UTF-8 comment corruption

- javascript/packages/linter/README.md
- javascript/packages/linter/src/cli.ts
- javascript/packages/linter/src/cli/argument-parser.ts
- javascript/packages/linter/src/cli/file-processor.ts
- javascript/packages/linter/src/cli/formatters/index.ts
- javascript/packages/linter/src/cli/formatters/json-formatter.ts
- javascript/packages/linter/src/cli/output-manager.ts
This pull request adds a new JSON flag to the linter CLI for structured JSON output. The implementation includes the new `--json` flag (shorthand for `--format=json`) and consistent JSON structure across all scenarios (success, errors, no files, no folder).
```bash
$ herb-lint file.html.erb --json
{
"offenses": [
{
"filename": "template.html.erb",
"message": "File must end with trailing newline",
"location": {
"start": { "line": 1, "column": 21 },
"end": { "line": 1, "column": 22 }
},
"severity": "error",
"code": "erb-requires-trailing-newline",
"source": "Herb Linter"
}
],
"summary": {
"filesChecked": 1,
"filesWithOffenses": 1,
"totalErrors": 1,
"totalWarnings": 0,
"totalOffenses": 1,
"ruleCount": 21
},
"timing": {
"startTime": "2025-08-14T16:00:48.845Z",
"duration": 27
},
"completed": …
```
> Linter: Add JSON output format

- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/erb/erb.test.ts
This pull request improves the formatter to prevent ERB content from being deleted when line wrapping occurs in text flow contexts.
Previously, when processing ERB tags that exceeded line length limits, the context restoration could happen after multiline formatting, causing the generated output to be discarded and resulting in empty HTML tags.
The fix ensures that context restoration occurs before calling `visitTextFlowChildrenMultiline` preserving the content.
Input:
```erb
<h3>
<%= link_to "Start", start_path %>&rsquo;s overview of <%= link_to "Section", section_path %>, <%= link_to "End", end_path %>.
</h3>
```
Before:
```erb
<h3>
</h3>
```
After:
```erb
<h3>
<%= link_to "Start", start_path %>&rsquo;s overview of <%= link_to "Section", section_path %>
, <%= link_to "End", end_path %>. …
```
> Formatter: Fix ERB content deletion during line wrapping

- package.json
Ever since merging #355 the CI build on main has been flaky and hangs. This pull request excludes the new `@herb-tools/tailwind-class-sorter` package to see if that's actually causing the issue.
> `--exclude=@herb-tools/tailwind-class-sorter`

- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/erb/unless.test.ts
This pull request updates the formatter so it doesn't incorrectly drop else clauses when formatting unless statements.
**Input:**
```erb
<% unless some_condition %>
<span>foo</span>
<% else %>
<span>bar</span>
<% end %>
```
**Before:**
```erb
<% unless some_condition %>
<span>foo</span>
<% end %>
```
**After:**
```erb
<% unless some_condition %>
<span>foo</span>
<% else %>
<span>bar</span>
<% end %>
```
Fixes #391
> Formatter: Fix `else` formatting in `ERBUnlessNode`

- javascript/packages/formatter/src/printer.ts
- javascript/packages/formatter/test/erb-formatter/erb-formatter-fixtures.test.ts
- javascript/packages/formatter/test/erb/begin.test.ts
- javascript/packages/formatter/test/erb/case.test.ts
- javascript/packages/formatter/test/erb/for.test.ts
- javascript/packages/formatter/test/erb/if.test.ts
- javascript/packages/formatter/test/erb/until.test.ts
- javascript/packages/formatter/test/erb/while.test.ts
This pull request refactors the printing of the ERB nodes to use the `this.printERBNode` function over the manual calls in the formatter. This now also more consistently adds whitespace around the Ruby content in ERB tags in all cases.
Previously this wasn't handled:
**Input:**
```erb
<%foo.each do |bar|%>
<p><%=baz%></p>
<%end%>
```
**Before:**
```erb
<%foo.each do |bar|%>
<p><%= baz %></p>
<% end %>
```
**After:**
```erb
<% foo.each do |bar| %>
<p><%= baz %></p>
<% end %>
```
Additionally, it adds some more tests to avoid any regression.
> Formatter: Fix ERB Tag spacing + more tests

- playground/index.html
- playground/src/controllers/playground_controller.js
This pull request adds two new buttons to to copy the content of the editor (on the left side) and to copy the result of the current tab (on the right side).
https://github.com/user-attachments/assets/d9e56a46-1a72-451a-841a-a848a6045aad
Additionally we have two new overlays to show that the formatter isn't formatting when there are errors in the document:
And if there are now diagnostics we show that too:
> Playground: Add Copy Buttons for editor and result and add overlays

- .rubocop.yml
- lib/herb/cli.rb
This pull request updates the Ruby CLI so that the `playground` command uses the playground hosted on herb-tools.dev by default. It also adds a `--local` option to be able to open a file in the local playground.
> CLI: `playground` command should open herb-tools.dev by default

- javascript/packages/formatter/src/cli.ts
- javascript/packages/formatter/test/cli.test.ts
- javascript/packages/formatter/test/fixtures/config.xml.erb
- javascript/packages/formatter/test/fixtures/example.xml.erb
- javascript/packages/formatter/test/fixtures/nested/manifest.xml.erb
- javascript/packages/formatter/test/xml-erb-integration.test.ts
- javascript/packages/linter/src/cli/argument-parser.ts
- javascript/packages/linter/test/xml-erb-linting.test.ts
This pull request updates the CLIs of both the formatter and linter to work the same way when passing passed arguments, especially in the way they handle files, paths, globs, or no arguments.
```bash
herb-lint                      # => "./**.html.erb"
herb-lint template.html.erb    # => "template.html.erb"
herb-lint app/                 # => "app/**.html.erb"
herb-lint "app/**.html.erb"    # => "app/**.html.erb"
herb-format                    # => "./**.html.erb"
herb-format template.html.erb  # => "template.html.erb"
herb-format app/               # => "app/**.html.erb"
herb-format "app/**.html.erb"  # => "app/**.html.erb"
```
> CLI: Bring Formatter and Linter CLI behavior closer together

- config.yml
- javascript/packages/formatter/src/format-printer.ts
- javascript/packages/linter/package.json
- javascript/packages/linter/src/rules/erb-prefer-image-tag-helper.ts
- javascript/packages/linter/test/rules/erb-prefer-image-tag-helper.test.ts
- javascript/packages/printer/src/erb-to-ruby-string-printer.ts
- javascript/packages/printer/src/index.ts
- javascript/packages/printer/test/erb-to-ruby-string-printer.test.ts
- templates/javascript/packages/core/src/node-type-guards.ts.erb
- templates/javascript/packages/core/src/nodes.ts.erb
This pull request introduces a new `ERBToRubyStringPrinter` that converts simple ERB expressions to a Ruby expression that outputs a String.
| In | Out |
| --- | --- |
| `hello world <%= hello %>` | `"hello world #{hello}"` |
| `hello world <% hello %>` | `"hello world "` |
| `Welcome <%= user.name %>!` | `"Welcome #{user.name}!"` |
| `<% if logged_in? %>Welcome<% else %>Login<% end %>` | `logged_in? ? "Welcome" : "Login"` |
| `<% if logged_in? %>Welcome<% else %>Login<% end %>!` | `"#{logged_in? ? "Welcome" : "Login"}!"` |
API:
```ts
import { ERBToRubyStringPrinter } from "@herb-tools/printer"
const result = Herb.parse("Hello <%= name %>!")
ERBToRubyStringPrinter.print(result)
// => "Hello #{name}!"
```
This pull request also refactors the `erb-prefer-image-tag-helper` linter rule to use …
> Printer: Introduce `ERBToRubyStringPrinter` to convert ERB to Ruby

- javascript/packages/formatter/src/format-printer.ts
- javascript/packages/formatter/test/erb-formatter/erb-formatter-fixtures.test.ts
- javascript/packages/formatter/test/erb/comment.test.ts
This pull request improves the way the formatter renders ERB Comments. It also solves the issue surfaced in #436 where the formatter duplicated the first line if it was on the same line as `<%#`.
> Formatter: Improve ERB Comment Rendering

- javascript/packages/core/src/ast-utils.ts
- javascript/packages/printer/src/identity-printer.ts
- javascript/packages/printer/test/nodes/html-close-tag-node.test.ts
This pull request updates the `IdentityPrinter` to also reconstruct the whitespace in the `HTMLCloseTag`. 
The parser was already adding the `WhitespaceNode`s to the `children` array of the `HTMLCloseTag` (done in #396), but the `IdentityPrinter` wasn't accounting for them.
Now these templates can also be fully reconstructed using the `IdentityPrinter`:
```html
<div></   div>
<div></div   >
<div></   div   >
```
Additionally, this pull request also adds some more AST helpers to the `@herb-tools/core` package to select nodes before/after a certain `Location` or `Position`.
> Printer: Also fully reconstruct whitespace in `HTMLCloseTag`

- javascript/packages/linter/src/rules/html-no-duplicate-ids.ts
- javascript/packages/linter/src/rules/rule-utils.ts
- javascript/packages/linter/test/rules/html-no-duplicate-ids.test.ts
- javascript/packages/printer/src/printer.ts
This pull request introduces a new `ControlFlowTrackingVisitor` base class which allows linter rules to track state across branches and loops.
With this new visitor we are now able to track state more strategically in branches.
```ts
interface MyRuleState {
counters: Map<string, number>
flags: boolean[]
}
interface MyBranchState {
savedCounters: Map<string, number>
}
class MyCustomRuleVisitor extends ControlFlowTrackingVisitor<MyRuleState, MyBranchState> {
protected onEnterControlFlow(controlFlowType: ControlFlowType, wasAlreadyInControlFlow: boolean): MyRuleState {
return { counters: new Map(), flags: [] }
}
protected onExitControlFlow(controlFlowType: ControlFlowType, wasAlreadyInControlFlow: boolean, stateToRestore: MyRuleState): void {
this.processCounters(stateToRestore.counters)
}
} …
```
> Linter: Introduce `ControlFlowTrackingVisitor` to handle control flow

- javascript/packages/linter/README.md
- javascript/packages/linter/src/cli.ts
- javascript/packages/linter/src/cli/argument-parser.ts
- javascript/packages/linter/src/cli/file-processor.ts
- javascript/packages/linter/src/cli/formatters/github-actions-formatter.ts
- javascript/packages/linter/src/cli/index.ts
- javascript/packages/linter/src/cli/output-manager.ts
- javascript/packages/linter/src/cli/summary-reporter.ts
- javascript/packages/linter/test/__snapshots__/cli.test.ts.snap
- javascript/packages/linter/test/cli.test.ts
- javascript/packages/linter/test/formatters/github-actions-formatter.test.ts
This pull request updates the linter CLI to output the highlighted part of the code in GitHub Actions annotation.
> Linter: Show highlighted offense preview in GitHub Actions annotations

- javascript/packages/formatter/src/cli.ts
- javascript/packages/formatter/test/cli.test.ts
This resolves https://github.com/marcoroth/herb/issues/440. The output matches the example in the issue with additional `printer` version
```
$ npx @herb-tools/formatter --version
Versions:
@herb-tools/formatter@0.6.1
@herb-tools/printer@0.6.1
@herb-tools/node-wasm@0.6.1
@herb-tools/core@0.6.1
libprism@1.4.0
libherb@0.6.1 (WebAssembly)
```
Can also do this dynamically, but results in some duplicates like `@herb-tools/core@0.6.1`
```
$ npx @herb-tools/formatter --version
Versions:
@herb-tools/formatter@0.6.1
@herb-tools/core@0.6.1
@herb-tools/printer@0.6.1
@herb-tools/node-wasm@0.6.1
@herb-tools/core@0.6.1
libprism@1.4.0
libherb@0.6.1 (WebAssembly)
```
> Add printer version to CLI in formatter --version command

- lib/herb/cli.rb
- lib/herb/project.rb
Fixes #347
```
ruby -I lib exe/herb analyze examples --no-log-file --non-interactive
Processing [1/16]: attributes_with_empty_value.html.erb
Processing [2/16]: begin.html.erb
Processing [3/16]: block.html.erb
Processing [4/16]: case_when.html.erb
Processing [5/16]: comment.html.erb
Processing [6/16]: doctype.html.erb
Processing [7/16]: erb.html.erb
Processing [8/16]: for.html.erb
Processing [9/16]: if_else.html.erb
Processing [10/16]: line-wrap.html.erb
Processing [11/16]: nested_if_and_blocks.html.erb
Processing [12/16]: simple_block.html.erb
Processing [13/16]: simple_erb.html.erb
Processing [14/16]: test.html.erb
Processing [15/16]: until.html.erb
Processing [16/16]: while.html.erb
Completed processing all files.
--- SUMMARY -------------------------------------------------------------- …
```
> Ruby CLI: Squelch Processing output when silent is passed in

- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- javascript/packages/browser/test/browser.test.ts
- javascript/packages/node-wasm/test/node-wasm.test.ts
- javascript/packages/node/test/node.test.ts
- test/herb_test.rb
Upgrade Prism to [`v1.5.1`](https://github.com/ruby/prism/releases/tag/v1.5.1), also see [`v1.5.0`](https://github.com/ruby/prism/releases/tag/v1.5.0).
> Bump Prism to `v1.5.1`

- src/parser.c
- test/parser/attributes_test.rb
- test/snapshots/parser/attributes_test/test_0038_Vue-style_directive_attribute_with_value_48a4fb492a8544d35ffb4d589f5a602c.txt
- test/snapshots/parser/attributes_test/test_0039_Vue-style_directive_attributes_multiple_4f1d1b98f3b9c869967323f090d9afee.txt
- test/snapshots/parser/attributes_test/test_0040_Vue-style_directive_attribute_without_value_14a36e2ed468092336d9f6080e939190.txt
- test/snapshots/parser/attributes_test/test_0041_Mixed_Vue_directives_and_regular_attributes_355d0da3aae174783058e2ccec41ac05.txt
- test/snapshots/parser/attributes_test/test_0042_Standalone_colon_with_space_is_invalid_c037b25064b31d22c6c195361999c5b8.txt
- test/snapshots/parser/attributes_test/test_0043_Colon_immediately_followed_by_attribute_name_is_valid_e30b590c384b162d5019345f8083bfdb.txt
- test/snapshots/parser/attributes_test/test_0044_Double_colon_is_invalid_f2b2354b82896dec0458b506ae56eb58.txt
- test/snapshots/parser/attributes_test/test_0045_Vue_directive_with_namespace-like_syntax_e3d2d0afe1a0d7a4f71d0831ed0a9306.txt
This pull request updates the parser to allow HTML Attributes to start with a colon, which is typical in the Vue.js style:
```html
<div :class="classes"></div>
```
Previously, this caused a syntax error: 
```js
@ UnexpectedError (location: (1:5)-(1:6))
├── message: "Unexpected Token. Expected: `TOKEN_IDENTIFIER, TOKEN_AT, TOKEN_ERB_START,TOKEN_WHITESPACE, or TOKEN_NEWLINE`, found: `TOKEN_COLON`."
├── description: "Unexpected Token"
├── expected: "TOKEN_IDENTIFIER, TOKEN_AT, TOKEN_ERB_START,TOKEN_WHITESPACE, or TOKEN_NEWLINE"
└── found: "TOKEN_COLON"
```
Now this parses as:
```js
@ HTMLAttributeNode (location: (1:5)-(1:21))
├── errors: []
├── name: 
│   └── @ HTMLAttributeNameNode (location: (1:5)-(1:11))
│       ├── errors: []
│       └── children: (1 item)
│           └── @ LiteralNode …
```
> Allow Colon `:` in HTML Attribute Names

- src/analyze.c
Removes the need to manually check for `invalid_yield`. Prism docs here: https://github.com/ruby/ruby/blob/4acfdb1faddf4d31d36abdfc74ea12229a6e59e3/prism/options.h#L178-L186
> Parser: Analyze parse errors as `partial_script`

- src/analyze.c
- src/include/pretty_print.h
- src/pretty_print.c
This PR renames the `pretty_print_analyed_ruby` c method to `pretty_print_analyzed_ruby`. Fixing a typo in the process.
> Fix typo in pretty_print_analyzed_ruby method

- javascript/packages/linter/src/rules/html-no-empty-attributes.ts
- javascript/packages/linter/test/__snapshots__/cli.test.ts.snap
- javascript/packages/linter/test/rules/html-no-empty-attributes.test.ts
This pull request updates the `html-no-empty-attributes` linter rule to allow for empty data attributes without an equal sign and attribute value.
This **is not** allowed:
```html
<div data-turbo-permament=""></div>
```
This **is** now allowed with this pull request:
```html
<div data-turbo-permament></div>
```
Resolves https://github.com/marcoroth/herb/issues/483
> Linter: Allow empty data attributes with no value

- src/herb.c
- src/include/parser.h
- src/parser.c
As painstakingly worked out with @marcoroth during Kaigi on Rails, macOS 26 Tahoe introduces a function named `parser_init` that can clobber the Herb function with the same name. Precompiled gems no longer crash on macOS 26 after this change to ensure the Herb functions will not be clobbered by the OS functions.
Resolves https://github.com/marcoroth/herb/issues/484
Resolves https://github.com/marcoroth/reactionview/issues/13
> Parser: Namespace Parser C functions

- javascript/packages/linter/docs/rules/README.md
This pull request makes a minor documentation fix to the Herb Linter rules list by correcting a broken link.
* Fixed the link for the `html-no-self-closing` rule in `README.md` by removing the duplicate `.md` extension.
> Docs: Fix link for `html-no-self-closing` rule in README

- javascript/packages/linter/docs/rules/README.md
- javascript/packages/linter/docs/rules/erb-comment-syntax.md
- javascript/packages/linter/src/default-rules.ts
- javascript/packages/linter/src/rules/erb-comment-syntax.ts
- javascript/packages/linter/src/rules/index.ts
- javascript/packages/linter/test/__snapshots__/cli.test.ts.snap
- javascript/packages/linter/test/rules/erb-comment-syntax.test.ts
- javascript/packages/vscode/package.json
Closes: #527 
Advances: https://github.com/marcoroth/herb/issues/537
This PR adds the rule `erb-comment-syntax`. It is the same rule implemented in [CommentSyntax](https://github.com/Shopify/erb_lint?tab=readme-ov-file#commentsyntax) of ERB Lint.
The rule itself avoid parsing errors in the action_view erb default parsing implementation.
Also the porting of ERB Lint rules to herb rules facilitates the adoption of Herb as a ERB Lint replacement.
> Linter: Implement `erb-comment-syntax`  linter rule

- javascript/packages/linter/test/rules/html-no-empty-headings.test.ts
- javascript/packages/linter/test/rules/parser-no-errors.test.ts
- src/lexer_peek_helpers.c
- test/parser/boolean_attributes_test.rb
- test/snapshots/parser/boolean_attributes_test/test_0007_boolean_attribute_on_void_element_followed_by_newline_and_ERB_tag_with_track_whitespace_865f46b916df0289c3b60c880f529e8b-b26dbda6d8a652930695c93bd07179f4.txt
- test/snapshots/parser/boolean_attributes_test/test_0008_boolean_attribute_on_void_element_followed_by_ERB_tag_with_track_whitespace_7a98c943c925e6943aaa2bec978901a9-b26dbda6d8a652930695c93bd07179f4.txt
- test/snapshots/parser/boolean_attributes_test/test_0009_boolean_attribute_on_void_element_followed_by_ERB_tag_with_track_whitespace_1d3295149578acc142f855bb3b75b3ec-b26dbda6d8a652930695c93bd07179f4.txt
This pull request updates the parser to fix a bug where an HTML element with a boolean attribute as the final attribute would cause a parser error when the `track_whitespace` parser option is set.
This snippet parses fine using `track_whitespace: false`
```html+erb
<input required><%= content %>
```
But with `track_whitespace: true` it would fail with:
```
Unexpected token. Expected: `TOKEN_ERB_START, TOKEN_HTML_DOCTYPE, TOKEN_HTML_COMMENT_START, TOKEN_IDENTIFIER, TOKEN_WHITESPACE, TOKEN_NBSP, TOKEN_AT, or TOKE`, found: `TOKEN_ERB_CONTENT`. Line 1:19
Unexpected token. Expected: `TOKEN_ERB_START, TOKEN_HTML_DOCTYPE, TOKEN_HTML_COMMENT_START, TOKEN_IDENTIFIER, TOKEN_WHITESPACE, TOKEN_NBSP, TOKEN_AT, or TOKE`, found: `TOKEN_ERB_END`. Line 1:28
```
Resolves #471 
Resolves #525 
Resolves #558
> Parser: Fix parsing boolean attributes with `track_whitespace`

- javascript/packages/linter/docs/rules/README.md
- javascript/packages/linter/docs/rules/erb-right-trim.md
- javascript/packages/linter/src/rules/erb-right-trim.ts
- javascript/packages/linter/src/rules/rule-utils.ts
- javascript/packages/linter/test/rules/erb-right-trim.test.ts
- templates/javascript/packages/core/src/visitor.ts.erb
This pull request introduces two new methods `visitNode(node: Node)` and `visitERBNode(node: ERBNode)` in the JavaScript visitor that allows to visit any node, or visit any ERB node. This is useful and allows us to improve the `erb-right-trim` introduced in #556.
This now updates the `erb-right-trim` to also handle cases where the right trimming is used when it has no effect (like on non-outputting ERB Nodes like `<%`).
/cc @domingo2000
> Add `visitNode` and `visitERBNode` methods to improve `erb-right-trim`

- javascript/packages/linter/src/rules/erb-require-whitespace-inside-tags.ts
This pull request updates the `erb-require-whitespace-inside-tags` linter rule to use the new `visitERBNode` method in the visitor introduced in #569.
> Linter Rule: Refactor `erb-require-whitespace-inside-tags` to use `visitERBNode`

- javascript/packages/linter/src/cli.ts
- javascript/packages/linter/src/cli/argument-parser.ts
Check first if the user just wants to see the version of their linter. If so, print and exit.
Closes #437
> Linter: Fix `--version` flag for CLI

- javascript/packages/formatter/src/cli.ts
- javascript/packages/formatter/test/cli.test.ts
This pull request updates the formatter CLI to print the `⚠️ Experimental Preview ...` warning on `stderr` instead of `stdout` to other tools can programmatically use the formatter output.
Resolves https://github.com/marcoroth/herb/issues/574
/cc @mnkhod
> Formatter: Print `Experimental Preview` warning on `stderr`

- src/analyze.c
- test/analyze/case_in_test.rb
- test/analyze/case_test.rb
- test/snapshots/analyze/case_in_test/test_0008_case_in_with_block_inside_in_clause_a5d7393ef0ab780cd777fd4d09413ac8.txt
- test/snapshots/analyze/case_in_test/test_0009_case_in_with_multiple_blocks_in_in_clause_8cdfe954fcb68cf29f71d5c05893547c.txt
- test/snapshots/analyze/case_in_test/test_0010_case_in_with_if_statement_inside_in_clause_51fcf7566215a5284ae1ee34c920837e.txt
- test/snapshots/analyze/case_test/test_0008_case_with_block_inside_when_adb20c2773fe1206d2b47123f8001e22.txt
- test/snapshots/analyze/case_test/test_0009_case_with_multiple_blocks_in_when_05f7d387314a95620a58ddc7f7d31b7b.txt
- test/snapshots/analyze/case_test/test_0010_case_with_nested_blocks_in_when_6e70c1bf60788969969296d35c409a47.txt
- test/snapshots/analyze/case_test/test_0011_case_with_block_in_multiple_when_clauses_3f35d3ebf6ea6eaf8e7b9bc7f8393a0f.txt
- test/snapshots/analyze/case_test/test_0012_case_with_if_statement_inside_when_ccc0bd511203c41d9274ccc360e736c2.txt
This pull request updates the parser to fix the analysis of nested control flow structures within `case/when` and `case/in` statements.
The following kind templates now have the properly nested structure:
```html+erb
<% case 1 %>
<% when 1 %>
<%= content_tag(:p) do %>
Yep
<% end %>
<% end %>
```
Resolves https://github.com/marcoroth/herb/issues/540
> Parser: Fix analysis of nested `case/when` and `case/in` parsing

- src/analyze.c
- test/analyze/case_test.rb
- test/snapshots/analyze/case_test/test_0013_case_with_yield_dc59b65969b8ef95076abc05c3907392.txt
This pull request updates the parser to analyze `yield`  inside `case` nodes as `ERBCaseNode` instead of `ERBYieldNode`.
The following templates:
```html+erb
<% case yield(:a) %>
<% when 'a' %>
aaa
<% end %>
```
Gets now parsed as:
```js
@ DocumentNode (location: (1:0)-(5:0))
└── children: (2 items)
├── @ ERBCaseNode (location: (1:0)-(4:9))
│   ├── tag_opening: "<%" (location: (1:0)-(1:2))
│   ├── content: " case yield(:a) " (location: (1:2)-(1:18))
│   ├── tag_closing: "%>" (location: (1:18)-(1:20))
│   ├── children: (1 item)
│   │   └── @ HTMLTextNode (location: (1:20)-(2:0))
│   │       └── content: "\n"
│   │
│   ├── conditions: (1 item)
│   │   └── @ ERBWhenNode (location: (2:0)-(2:14))
│   │       ├── tag_opening: "<%" (location: (2:0)-(2:2))
│   │       ├── content: " when 'a' " …
```
> Parser: Analyze `case` statements with `yield` as `ERBCaseNode`

- src/main.c
This pull request updates the C-CLI to also call `herb_analyze_parse_tree` in the `parse` command, so that the `ERBContentNodes` also get analyzed in a HTML+ERB document.
AS discussed in https://github.com/marcoroth/herb/issues/406#issuecomment-3350166452
> C: Also call `analyze` in C-CLI `parse` command

- bin/leaks_parse
- ext/herb/extension.c
- javascript/packages/node/extension/herb.cpp
- src/analyze.c
- src/buffer.c
- src/extract.c
- src/herb.c
- src/include/buffer.h
- src/io.c
- src/lexer.c
- src/main.c
- src/parser.c
- src/token.c
- test/c/test_buffer.c
- test/c/test_json.c
- test/c/test_lex.c
- test/c/test_token.c
- wasm/herb-wasm.cpp
This pull request is an alternative to #579 and reworks the buffer to not have a default capacity anymore, but instead, let the caller decide how big the initial buffer capacity should be. 
This also allows callers to request enough capacity upfront if they know the approximate or exact buffer buffer length, which then doesn't need any buffer capacity expansions at a later point, thus removing the need to reallocate.
Closes #579
> C: Favor explicit buffer capacity over default capacity
